// Turn Retrosheet's CurrentNames.csv into this repo's MLB name table.
//
//   node scripts/names.mjs > data/reference/mlb-names.csv
//
// This is the file football does not have, and the difference shapes both
// sports' name resolution:
//
//   baseball  Retrosheet publishes franchise id, historical id, city, nickname
//             and the exact dates each applied. So a 1969 Brewers game can be
//             labelled "Seattle Pilots", which is what it was.
//   football  nothing equivalent exists. data/reference/nfl-franchises.csv is a
//             starting list whose dates are explicitly NOT eras, so NFL names
//             resolve to the current franchise name regardless of date — the
//             same thing the football site has always done.
//
// Committed rather than fetched at build time, because FiveThirtyEight's
// endpoints going dark is the worked example of why a third-party file you
// depend on should live in the checkout. Refetch by rerunning this.
//
// Retrosheet asks that anything using their data carry their notice, and it is
// written into the output header.

import { parseCsv } from '../lib/csv.js';

const SOURCE = 'https://www.retrosheet.org/CurrentNames.csv';

// The file has no header row. These are its columns, in order.
const COLUMNS = ['current', 'code', 'league', 'division', 'city', 'nickname', 'alt', 'from', 'to', 'venueCity', 'state'];

/** Retrosheet writes M/D/YYYY; everything here compares dates as ISO strings. */
export function isoDate(american) {
	if (!american) return '';
	const m = String(american).match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);
	if (!m) return '';
	const [, mm, dd, yyyy] = m;
	return `${yyyy}-${mm.padStart(2, '0')}-${dd.padStart(2, '0')}`;
}

/** One row per (code, name, span). Consecutive rows that differ only by league
 *  or division are merged, because a club moving from the AL East to the AL
 *  Central did not change its name and three rows saying "Milwaukee Brewers"
 *  is noise in a name table. */
export function collapseNames(rows) {
	const out = [];
	for (const r of rows) {
		const name = `${r.city} ${r.nickname}`.trim();
		const last = out[out.length - 1];
		if (last && last.code === r.code && last.name === name) {
			// An open-ended `to` wins from EITHER side: it means "still current",
			// and a span that is current cannot be ended by merging a closed one
			// into it.
			//
			// The first version only checked the incoming row, so with an open
			// span already accumulated and a closed row arriving, `r.to > last.to`
			// compared a date against '' — which is true for every date — and
			// the franchise silently acquired an end date. Ordered input hides
			// it, which is why the mutant that deleted the guard entirely also
			// survived: both versions were wrong in the same direction.
			last.to = (last.to === '' || r.to === '') ? '' : (r.to > last.to ? r.to : last.to);
			continue;
		}
		out.push({ current: r.current, code: r.code, name, from: r.from, to: r.to });
	}
	return out;
}

const esc = (s) => (/[",]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s);

async function main() {
	const res = await fetch(SOURCE);
	if (!res.ok) throw new Error(`${SOURCE} -> ${res.status}`);
	const text = await res.text();

	// parseCsv takes the first line as a header, and this file has none.
	const rows = parseCsv([COLUMNS.join(','), text].join('\n'))
		.filter((r) => r.code)
		.map((r) => ({ ...r, from: isoDate(r.from), to: isoDate(r.to) }));

	const names = collapseNames(rows);

	const out = [
		'# Franchise names by date, for MLB.',
		'#',
		'# Generated by scripts/names.mjs from Retrosheet\'s CurrentNames.csv.',
		`# Source: ${SOURCE}`,
		'#',
		'# Unlike data/reference/nfl-divisions.csv, these dates ARE real eras: a',
		'# game on 1969-06-01 was played by the Seattle Pilots, and that is what',
		'# this file says. Football has no equivalent, which is why NFL names',
		'# resolve to the current franchise name regardless of date.',
		'#',
		'# An empty `to` means the name is current.',
		'#',
		'# The information used here was obtained free of charge from and is',
		'# copyrighted by Retrosheet. Interested parties may contact Retrosheet at',
		'# https://www.retrosheet.org.',
		'code,name,from,to,current',
		...names.map((n) => [n.code, esc(n.name), n.from, n.to, n.current].join(',')),
	];
	process.stdout.write(`${out.join('\n')}\n`);
	process.stderr.write(`  ${names.length} name spans across ${new Set(names.map((n) => n.current)).size} franchises\n`);
	return 0;
}

if (process.argv[1]?.endsWith('names.mjs')) process.exit(await main());
